### ISSUE TITLE
RuntimeError: Layer data_mul_2528825292/copy_const not found in network

### ISSUE THREAD

**Issue by edhgit** [intel-iot-devkit/pneumonia-classification#2]
Hello,

When implementing this interesting application, I get the follwoing runtime error:

    RuntimeError: Layer data_mul_2528825292/copy_const not found in network.
Details are given below.
Any help is greatly appreciated.

Environment:
------------
OS: Ubuntu 18.04.1 LTS
Language: Python 3.6.9
OpenVINO toolkit: 2020 R1 release

Implementation steps
---------------------
    (venv) vax:~$ unzip pneumonia-classification-master.zip
    (venv) vax:~$ cd pneumonia-classification-master/
    (venv) vax:~/pneumonia-classification-master$ chmod +x setup.sh
    (venv) vax:~/pneumonia-classification-master$ ./setup.sh
    ...
    [ SUCCESS ] Generated IR version 10 model.
    [ SUCCESS ] XML file: ~/pneumonia-classification-master/resources/FP32/model.xml
    [ SUCCESS ] BIN file:     ~/pneumonia-classification-master/resources/FP32/model.bin
    [ SUCCESS ] Total execution time: 68.01 seconds.
    [ SUCCESS ] Memory consumed: 445 MB.
    ...
    [ SUCCESS ] Generated IR version 10 model.
    [ SUCCESS ] XML file:     ~/pneumonia-classification-master/resources/FP16/model.xml
    [ SUCCESS ] BIN file: ~/pneumonia-classification-master/resources/FP16/model.bin
    [ SUCCESS ] Total execution time: 66.36 seconds.
    [ SUCCESS ] Memory consumed: 441 MB.
    (venv) vax:~/pneumonia-classification-master$ source /opt/intel/openvino/bin/setupvars.sh
    [setupvars.sh] OpenVINO environment initialized

Running the application
----------------------
    (venv) vax:~/pneumonia-classification-master$ cd application/
    (venv) vax:~/pneumonia-classification-master/application$ python3 pneumonia_classification.py -m ../resources/FP32/model.xml
    [ INFO ] Loading network files:
            ../resources/FP32/model.xml
            ../resources/FP32/model.bin
    [ INFO ] Initializing plugin for CPU device...
    [ INFO ] Reading IR...
    [ INFO ] Loading IR to the plugin...
    Traceback (most recent call last):
      File "pneumonia_classification.py", line 376, in <module>
        sys.exit(main() or 0)
      File "pneumonia_classification.py", line 338, in main
        infer_network.load_model_for_activation_map(bn, 0, device)
      File "~/pneumonia-classification-master/application/inference.py", line 189, in load_model_for_activation_map
        self.net.add_outputs(bn)
      File "ie_api.pyx", line 1109, in openvino.inference_engine.ie_api.IENetwork.add_outputs
    RuntimeError: Layer data_mul_2528825292/copy_const not found in network

Checking that the missing Layer is present in the model.xml description
-------------------------------------------------------------------
    (venv) vax:~/pneumonia-classification-master/application$ grep data_mul_2528825292/copy_const ../resources/FP32/model.xml
                <layer id="365" name="data_mul_2528825292/copy_const" type="Const" version="opset1">

**Comment by MandipJ** [comment]
@edhgit 
This application has been tested on **OpenVINO 2019 R3** and is yet to be updated for OpenVINO 2020.
